FROM mcr.microsoft.com/devcontainers/base:alpine-3.19

RUN apk --update add jekyll ruby-dev

CMD echo "export GEM_HOME=/home/vscode/.gem" >> ~/.zshrc
CMD echo "export GEM_HOME=/home/vscode/.gem" >> ~/.bashrc
